
name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          submodules: "recursive"

      - name: Install Lua
        uses: hishamhm/gh-actions-lua@master
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Install LuaRocks
        uses: hishamhm/gh-actions-luarocks@master

      - name: Build ltreesitter
        run: |
          luarocks make

      # TODO: are there actions to install parsers anywhere?
      - name: Install tree-sitter-c
        run: |
          git clone --depth=1 https://github.com/tree-sitter/tree-sitter-c.git
          cd tree-sitter-c
          mkdir -p ~/.tree-sitter/bin
          cc src/parser.c -shared -fPIC -o ~/.tree-sitter/bin/c.so

      - name: Install busted
        run: |
          luarocks install busted

      - name: Run tests
        run: |
          env LTREESITTER_TEST_LOAD_C_PARSER=~/.tree-sitter/bin/c.so busted -o utfTerminal


