
name: test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Install tree-sitter
        run: |
          git clone https://github.com/tree-sitter/tree-sitter
          cd tree-sitter
          make all
          sudo make install

      - name: Install tree-sitter-c
        run: |
          git clone --depth=1 https://github.com/tree-sitter/tree-sitter-c.git
          cd tree-sitter-c
          mkdir -p ~/.tree-sitter/bin
          cc src/parser.c -shared -fPIC -o ~/.tree-sitter/bin/c.so

      - name: Install Lua
        uses: leafo/gh-actions-lua@v10.0.0
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - name: Install LuaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0

      - name: Build
        run: |
          luarocks install busted
          luarocks make

      - name: Test
        run: |
          busted -o utfTerminal


